resources:
  - ../../base
patchesStrategicMerge:
  - fastapi-patch.yaml
configMapGenerator:
  - name: fastapi-config
    literals:
      - DEBUG=false  # Généralement, on désactive le mode DEBUG en production
