apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  template:
    spec:
      containers:
        - name: fastapi
          image: datascientest/fastapi:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: DEBUG  # Utilisez la valeur du ConfigMap ici
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config  # Le nom du ConfigMap généré
                  key: DEBUG
